const NextServer = require('next/dist/server/next-server').default
const http = require('http')
const path = require('path')
const fs = require('fs')

process.env.NODE_ENV = 'production'
process.chdir(__dirname)

const currentPort = parseInt(process.env.PORT, 10) || 3000
const hostname = process.env.HOSTNAME || '0.0.0.0'

// Load the official configuration generated by Next.js during build
const config = JSON.parse(fs.readFileSync(path.join(__dirname, '.next/required-server-files.json'), 'utf-8'))

const nextServer = new NextServer({
  hostname,
  port: currentPort,
  dir: __dirname,
  dev: false,
  customServer: false,
  conf: config.config,
})

const handler = nextServer.getRequestHandler()

const server = http.createServer(async (req, res) => {
  try {
    await handler(req, res)
  } catch (err) {
    console.error(err)
    res.statusCode = 500
    res.end('Internal Server Error')
  }
})

// CRITICAL: Call listen ONLY with the port (or socket path) and no hostname.
// This allows Phusion Passenger to intercept the listen call instantly and bind to its Unix socket.
server.listen(process.env.PORT || 3000, (err) => {
  if (err) {
    console.error('Failed to start server:', err)
    process.exit(1)
  }
  console.log(`[FSH] Server listening on ${process.env.PORT || 3000}`)
})
