/**
 * Hostinger Node.js Production Entry Point
 * 
 * With next output: 'standalone', Next.js generates a self-contained server.
 * We run the generated .next/standalone/server.js directly.
 * 
 * This avoids duplicate instance spawning since Hostinger's Passenger/PM2
 * will manage the process lifecycle. We explicitly set PORT and HOSTNAME
 * before starting.
 */

process.env.NODE_ENV = 'production';
process.env.PORT = process.env.PORT || '3000';
process.env.HOSTNAME = process.env.HOSTNAME || '0.0.0.0';

// Start the standalone server generated by next build
require('./.next/standalone/server.js');
