/**
 * Hostinger Node.js Production Entry Point
 * Runs the Next.js standalone server generated by `next build`
 */

const port = process.env.PORT || 3000;
const hostname = process.env.HOSTNAME || '0.0.0.0';

// Log startup info so we can diagnose in runtime logs
console.log('=== FreshSabjiHub Server Starting ===');
console.log(`NODE_ENV  : ${process.env.NODE_ENV}`);
console.log(`PORT env  : ${process.env.PORT}`);
console.log(`Using port: ${port}`);
console.log(`Hostname  : ${hostname}`);
console.log(`CWD       : ${process.cwd()}`);

// Set required env vars for Next.js standalone
process.env.NODE_ENV = process.env.NODE_ENV || 'production';
process.env.PORT = String(port);
process.env.HOSTNAME = hostname;

// Verify the standalone server exists before requiring it
const path = require('path');
const fs = require('fs');

const standaloneServerPath = path.join(__dirname, '.next', 'standalone', 'server.js');

if (!fs.existsSync(standaloneServerPath)) {
  console.error('ERROR: .next/standalone/server.js not found!');
  console.error('The build may not have completed properly.');
  console.error('Expected at:', standaloneServerPath);
  process.exit(1);
}

console.log('Loading standalone server from:', standaloneServerPath);

// Start the standalone server
require(standaloneServerPath);
